version: "3.8"

services:
  db:
    container_name: PostgreSQL
    image: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    
  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  
  fastapi:
    container_name: fastapi
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  
  celery:
    container_name: celery
    build: .
    command: celery -A utils.celery_worker.app worker --loglevel=info
    env_file:
      - ./.env
    depends_on:
      - fastapi
      - rabbitmq
