version: "3.8"

services:
  db:
    container_name: PostgreSQL
    image: postgres
    #restart: on-failure
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=my_db
    volumes:

      - ./postgres-data:/var/lib/postgresql/data

    env_file:
      - ./.env
    
  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq

  
  fastapi:
    container_name: fastapi
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    
    ports:
      - "8000:8000"
    environment:
      - SQLALCHAMY_DATABASE_URL=postgresql://admin:admin@db:5432/my_db
    env_file:
      - ./.env
    depends_on:
      - db
  
  celery:
    container_name: celery
    build: .
    command: celery -A tasks worker --loglevel=info -P solo
    env_file:
      - ./.env
    depends_on:
      - fastapi
      - rabbitmq
